[project]
name = "finance-wiki"
description = "Mi wiki personal sobre finanzas personales e inversión en Español"
authors = [
    {name = "Daniel Bazo Correa", email = "none@none.com"},
]
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11"
classifiers = [
    "Intended Audience :: Education",
    "Natural Language :: Spanish",
    "Topic :: Documentation",
    "Topic :: Office/Business :: Financial :: Investment",
]
keywords = ["finanzas personales", "inversión", "mercados", "wiki"]
dependencies = [
    "zensical==0.0.60",
]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true } }]
environments = [
    "sys_platform == 'linux'",
]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'"
]
